// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://styeczxtusehjmappqrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0eWVjenh0dXNlaGptYXBwcXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTY1MjEsImV4cCI6MjA3MDY3MjUyMX0.UAhm72-aWShjoG5W64zCzXAu3FrQDG6Dl3w07gI94aY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage, // Use sessionStorage so sessions expire when tab is closed
    persistSession: true,
    autoRefreshToken: true,
  }
});